server:
  port: 8095
    
kafka:
  bootstrap-servers: localhost:9092
  topic:
    blogpost_topic: iblog_post_latest

spring:
  data:
    elasticsearch: 
      cluster-nodes: localhost:9300
## App Properties
app:
 jwtSecret: JWTSuperSecretKey
 jwtExpirationInMs: 604800000
 
logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR