server:
  port: 8095
    
kafka:
  bootstrap-servers: localhost:9092
  topic:
    blogpost_topic: iblog_post_latest

elasticsearch:
  clustername: elasticsearch
  host: localhost
  port: 9200


spring:
  data:
    elasticsearch: 
      cluster-nodes: localhost:9200
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages:iblog.core.model.*
## App Properties
app:
 jwtSecret: JWTSuperSecretKey
 jwtExpirationInMs: 604800000
 
logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR