spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order_microservice
  activemq:
    broker: tcp://localhost:61616
    user: admin
    password: admin    

logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR

server:
  port: 8094
  
## App Properties
app:
 jwtSecret: JWTSuperSecretKey
 jwtExpirationInMs: 604800000