spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR

server:
  port: 7094

adminChannel: adminChannel

