server:
  port: 9091
  
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ishop_products?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create
  jakson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto = update

## Hibernate Logging
#logging.level.org.hibernate.SQL= DEBUG

## Jackson Properties
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS= false
#spring.jackson.time-zone= UTC

## App Properties
app:
 jwtSecret: JWTSuperSecretKey
 jwtExpirationInMs: 604800000
 
logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR