spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog_post_microservice  
    
logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR

server:
  port: 8094

kafka:
  bootstrap-servers: localhost:9092
  topic:
    blogpost_topic: iblog_post

  
## App Properties
app:
 jwtSecret: JWTSuperSecretKey
 jwtExpirationInMs: 604800000
