spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping_microservice

logging:
  level:
    root: ERROR
    org:
      springframework.: ERROR

server:
  port: 9083
