server:
  port: 8080
  
zuul:
  prefix: /api
  sensitiveHeaders:
  routes:
    oauth:
      path: /oauth/**
      serviceId: iShopOAuth2Service 
    product:
      path: /product/**
      serviceId: iShopProductService
    customer:
      path: /customer/**
      serviceId: iShopCustomerService
    shopping:
      path: /shopping/**
      serviceId: iShopShoppingService
    order:
      path: /order/**
      serviceId: iShopOrderService 